# Generated by Django 4.2.7 on 2023-11-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('dateofBirth', models.DateTimeField(null=True)),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
    ]
