# Generated by Django 4.2.7 on 2023-11-08 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formpractise', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=20)),
                ('last_name', models.TextField(max_length=20)),
                ('location', models.TextField(max_length=20)),
                ('email_address', models.EmailField(max_length=254, unique=True)),
                ('dateofBirth', models.DateTimeField(null=True)),
                ('gender', models.BooleanField(choices=[(False, 'Male'), (False, 'Female'), (False, 'Other')], default=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
