# Generated by Django 4.2.7 on 2023-11-09 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formpractise', '0004_student_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateofBirth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='fathers_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_name',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='location',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='mothers_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
