# Generated by Django 4.2.7 on 2023-11-09 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formpractise', '0005_alter_student_dateofbirth_alter_student_fathers_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='dateofBirth',
            field=models.DateField(),
        ),
    ]
