# Generated by Django 4.2.7 on 2023-11-13 04:40

import Formpractise.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formpractise', '0009_alter_student_application_alter_student_dateofbirth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='application',
            field=models.ImageField(default='applications/default.jpg', upload_to=Formpractise.models.unique_img),
        ),
    ]
